import React from 'react';
import {
    Search,
    Briefcase,
    FileText,
    BarChart3,
    User,
    Settings,
    Plus,
    Check,
    X,
    ChevronDown,
    ChevronRight,
    ExternalLink,
    Download,
    Upload,
    MessageCircle,
    Bot,
    Send,
    Mic,
    MicOff,
    Play,
    Pause,
    RotateCcw,
    Eye,
    EyeOff,
    Calendar,
    Clock,
    MapPin,
    DollarSign,
    Star,
    TrendingUp,
    AlertCircle,
    CheckCircle,
    XCircle,
    Info,
    Home,
    Menu,
    Bell,
    Mail,
    Phone,
    Globe,
    Github,
    Linkedin,
    Twitter,
    Trash2,
    Edit,
    Copy,
    Share,
    Filter,
    RefreshCw,
    Zap,
    Target,
    Award,
    BookOpen,
    GraduationCap,
    Building,
    Users,
    Heart,
    ThumbsUp,
    ThumbsDown,
    Flag,
    Bookmark,
    Archive,
    Folder,
    FolderOpen,
    File,
    Image,
    Video,
    Music,
    Code,
    Terminal,
    Database,
    Server,
    Cloud,
    Wifi,
    WifiOff,
    Lock,
    Unlock,
    Shield,
    Key,
    CreditCard,
    ShoppingCart,
    Package,
    Truck,
    Plane,
    Car,
    Bike,
    Train,
    Bus,
    Ship,
    Rocket,
    Gamepad2,
    Camera,
    Headphones,
    Speaker,
    Volume2,
    VolumeX,
    Battery,
    BatteryLow,
    Bluetooth,
    Usb,
    HardDrive,
    Cpu,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Watch,
    Printer,
    Scanner,
    Keyboard,
    Mouse,
    Webcam,
    Microphone,
    Lightbulb,
    Sun,
    Moon,
    CloudRain,
    CloudSnow,
    Umbrella,
    Thermometer,
    Wind,
    Compass,
    Navigation,
    Map,
    Route,
    Anchor,
    Tent,
    TreePine,
    Mountain,
    Waves,
    Flame,
    Snowflake,
    Flower,
    Leaf,
    Bug,
    Fish,
    Bird,
    Cat,
    Dog,
    Rabbit,
    Turtle,
    Squirrel,
    PawPrint,
    Bone,
    Apple,
    Cherry,
    Grape,
    Orange,
    Banana,
    Carrot,
    Pizza,
    Coffee,
    Wine,
    Beer,
    IceCream,
    Cake,
    Cookie,
    Candy,
    Utensils,
    ChefHat,
    Soup,
    Salad,
    Sandwich,
    Croissant,
    Donut,
    Pretzel,
    Popcorn,
    Peanut,
    Milk,
    Egg,
    Cheese,
    Bread,
    Meat,
    Vegetable,
    Fruit,
    Grain,
    Spice,
    Salt,
    Pepper,
    Sugar,
    Honey,
    Oil,
    Vinegar,
    Sauce,
    Ketchup,
    Mustard,
    Mayo,
    Pickle,
    Onion,
    Garlic,
    Ginger,
    Chili,
    Herb,
    Mint,
    Basil,
    Rosemary,
    Thyme,
    Oregano,
    Parsley,
    Cilantro,
    Dill,
    Sage,
    Lavender,
    Rose,
    Tulip,
    Sunflower,
    Daisy,
    Lily,
    Orchid,
    Cactus,
    Succulent,
    Fern,
    Moss,
    Mushroom,
    Acorn,
    Pinecone,
    Shell,
    Coral,
    Starfish,
    Jellyfish,
    Octopus,
    Shark,
    Whale,
    Dolphin,
    Penguin,
    Flamingo,
    Eagle,
    Owl,
    Parrot,
    Peacock,
    Swan,
    Duck,
    Chicken,
    Rooster,
    Turkey,
    Pig,
    Cow,
    Horse,
    Sheep,
    Goat,
    Deer,
    Bear,
    Wolf,
    Fox,
    Lion,
    Tiger,
    Elephant,
    Giraffe,
    Zebra,
    Rhino,
    Hippo,
    Monkey,
    Gorilla,
    Panda,
    Koala,
    Kangaroo,
    Sloth,
    Hedgehog,
    Bat,
    Spider,
    Butterfly,
    Bee,
    Ladybug,
    Dragonfly,
    Ant,
    Snail,
    Worm,
    Lizard,
    Snake,
    Frog,
    Crocodile
} from 'lucide-react';

const iconMap = {
    // Navigation and UI
    'search': Search,
    'briefcase': Briefcase,
    'file-text': FileText,
    'bar-chart': BarChart3,
    'user': User,
    'settings': Settings,
    'plus': Plus,
    'check': Check,
    'x': X,
    'close': X,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'external-link': ExternalLink,
    'download': Download,
    'upload': Upload,
    'home': Home,
    'menu': Menu,
    'bell': Bell,
    'mail': Mail,
    'phone': Phone,
    'globe': Globe,
    'github': Github,
    'linkedin': Linkedin,
    'twitter': Twitter,
    'trash': Trash2,
    'edit': Edit,
    'copy': Copy,
    'share': Share,
    'filter': Filter,
    'refresh': RefreshCw,
    'zap': Zap,
    'target': Target,
    'award': Award,
    'book': BookOpen,
    'graduation-cap': GraduationCap,
    'building': Building,
    'users': Users,
    'heart': Heart,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    'flag': Flag,
    'bookmark': Bookmark,
    'archive': Archive,
    'folder': Folder,
    'folder-open': FolderOpen,
    'file': File,
    'image': Image,
    'video': Video,
    'music': Music,
    'code': Code,
    'terminal': Terminal,
    'database': Database,
    'server': Server,
    'cloud': Cloud,
    'wifi': Wifi,
    'wifi-off': WifiOff,
    'lock': Lock,
    'unlock': Unlock,
    'shield': Shield,
    'key': Key,
    'credit-card': CreditCard,
    'shopping-cart': ShoppingCart,
    'package': Package,
    'truck': Truck,
    'plane': Plane,
    'car': Car,
    'bike': Bike,
    'train': Train,
    'bus': Bus,
    'ship': Ship,
    'rocket': Rocket,
    'gamepad': Gamepad2,
    'camera': Camera,
    'headphones': Headphones,
    'speaker': Speaker,
    'volume': Volume2,
    'volume-x': VolumeX,
    'battery': Battery,
    'battery-low': BatteryLow,
    'bluetooth': Bluetooth,
    'usb': Usb,
    'hard-drive': HardDrive,
    'cpu': Cpu,
    'monitor': Monitor,
    'smartphone': Smartphone,
    'tablet': Tablet,
    'laptop': Laptop,
    'watch': Watch,
    'printer': Printer,
    'scanner': Scanner,
    'keyboard': Keyboard,
    'mouse': Mouse,
    'webcam': Webcam,
    'microphone': Microphone,
    'lightbulb': Lightbulb,
    'sun': Sun,
    'moon': Moon,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    'umbrella': Umbrella,
    'thermometer': Thermometer,
    'wind': Wind,
    'compass': Compass,
    'navigation': Navigation,
    'map': Map,
    'route': Route,
    'anchor': Anchor,
    'tent': Tent,
    'tree': TreePine,
    'mountain': Mountain,
    'waves': Waves,
    'flame': Flame,
    'snowflake': Snowflake,
    'flower': Flower,
    'leaf': Leaf,
    'bug': Bug,
    'fish': Fish,
    'bird': Bird,
    'cat': Cat,
    'dog': Dog,
    'rabbit': Rabbit,
    'turtle': Turtle,
    'squirrel': Squirrel,
    'paw-print': PawPrint,
    'bone': Bone,
    'apple': Apple,
    'cherry': Cherry,
    'grape': Grape,
    'orange': Orange,
    'banana': Banana,
    'carrot': Carrot,
    'pizza': Pizza,
    'coffee': Coffee,
    'wine': Wine,
    'beer': Beer,
    'ice-cream': IceCream,
    'cake': Cake,
    'cookie': Cookie,
    'candy': Candy,
    'utensils': Utensils,
    'chef-hat': ChefHat,
    'soup': Soup,
    'salad': Salad,
    'sandwich': Sandwich,
    'croissant': Croissant,
    'donut': Donut,
    'pretzel': Pretzel,
    'popcorn': Popcorn,
    'peanut': Peanut,
    'milk': Milk,
    'egg': Egg,
    'cheese': Cheese,
    'bread': Bread,
    'meat': Meat,
    'vegetable': Vegetable,
    'fruit': Fruit,
    'grain': Grain,
    'spice': Spice,
    'salt': Salt,
    'pepper': Pepper,
    'sugar': Sugar,
    'honey': Honey,
    'oil': Oil,
    'vinegar': Vinegar,
    'sauce': Sauce,
    'ketchup': Ketchup,
    'mustard': Mustard,
    'mayo': Mayo,
    'pickle': Pickle,
    'onion': Onion,
    'garlic': Garlic,
    'ginger': Ginger,
    'chili': Chili,
    'herb': Herb,
    'mint': Mint,
    'basil': Basil,
    'rosemary': Rosemary,
    'thyme': Thyme,
    'oregano': Oregano,
    'parsley': Parsley,
    'cilantro': Cilantro,
    'dill': Dill,
    'sage': Sage,
    'lavender': Lavender,
    'rose': Rose,
    'tulip': Tulip,
    'sunflower': Sunflower,
    'daisy': Daisy,
    'lily': Lily,
    'orchid': Orchid,
    'cactus': Cactus,
    'succulent': Succulent,
    'fern': Fern,
    'moss': Moss,
    'mushroom': Mushroom,
    'acorn': Acorn,
    'pinecone': Pinecone,
    'shell': Shell,
    'coral': Coral,
    'starfish': Starfish,
    'jellyfish': Jellyfish,
    'octopus': Octopus,
    'shark': Shark,
    'whale': Whale,
    'dolphin': Dolphin,
    'penguin': Penguin,
    'flamingo': Flamingo,
    'eagle': Eagle,
    'owl': Owl,
    'parrot': Parrot,
    'peacock': Peacock,
    'swan': Swan,
    'duck': Duck,
    'chicken': Chicken,
    'rooster': Rooster,
    'turkey': Turkey,
    'pig': Pig,
    'cow': Cow,
    'horse': Horse,
    'sheep': Sheep,
    'goat': Goat,
    'deer': Deer,
    'bear': Bear,
    'wolf': Wolf,
    'fox': Fox,
    'lion': Lion,
    'tiger': Tiger,
    'elephant': Elephant,
    'giraffe': Giraffe,
    'zebra': Zebra,
    'rhino': Rhino,
    'hippo': Hippo,
    'monkey': Monkey,
    'gorilla': Gorilla,
    'panda': Panda,
    'koala': Koala,
    'kangaroo': Kangaroo,
    'sloth': Sloth,
    'hedgehog': Hedgehog,
    'bat': Bat,
    'spider': Spider,
    'butterfly': Butterfly,
    'bee': Bee,
    'ladybug': Ladybug,
    'dragonfly': Dragonfly,
    'ant': Ant,
    'snail': Snail,
    'worm': Worm,
    'lizard': Lizard,
    'snake': Snake,
    'frog': Frog,
    'crocodile': Crocodile,
    
    // Chat and communication
    'chat-bubble-left-right': MessageCircle,
    'assistant': Bot,
    'send': Send,
    'mic': Mic,
    'mic-off': MicOff,
    'play': Play,
    'pause': Pause,
    'rotate-ccw': RotateCcw,
    'eye': Eye,
    'eye-off': EyeOff,
    'calendar': Calendar,
    'clock': Clock,
    'map-pin': MapPin,
    'dollar-sign': DollarSign,
    'star': Star,
    'trending-up': TrendingUp,
    'alert-circle': AlertCircle,
    'check-circle': CheckCircle,
    'x-circle': XCircle,
    'info': Info
};

const Icon = ({ icon, className = '', size = 24, ...props }) => {
    const IconComponent = iconMap[icon];
    
    if (!IconComponent) {
        console.warn(`Icon "${icon}" not found`);
        return <div className={`inline-block ${className}`} style={{ width: size, height: size }} {...props} />;
    }
    
    return <IconComponent className={className} size={size} {...props} />;
};

export { Icon };

